### ISSUE TITLE
Add kinesis waiter for deleting a stream

### ISSUE THREAD

**Issue by thomasdziedzic** [brendanhay/amazonka#100]
Something like the dynamodb waiter for deleting a table

**Comment by brendanhay** [comment]
Do you have any suggestions (similar to the [service definition](https://github.com/boto/botocore/blob/60e72b22bdebfa83e9b964aca232c7cad572212e/botocore/data/aws/kinesis/2013-12-02.waiters.json)) for how this should behave?

I'd initially try to propose they add it upstream, since if I add it to the overrides it risks being superseded by whatever Amazon adds to the definitions in the future.

**Comment by brendanhay** [comment]
Closing this due to lack of info - and dependency on having it introduced upstream.
