### ISSUE TITLE
`ListParts` `FromXML` instance

### ISSUE THREAD

**Issue by etorreborre** [brendanhay/amazonka#122]
I don't know exactly how the `ListParts` code was generated but it looks like the XML parsing is broken now for parts. It is [now](https://github.com/brendanhay/amazonka/blob/develop/amazonka-s3/gen/Network/AWS/S3/ListParts.hs#L275):
```
        <*> x .@? "Part" .!@ mempty
```
and it used to be
```
        <*> parseXML
```

With the current version I get an empty list on `ListParts` requests while I get them correctly with the old version.

**Comment by brendanhay** [comment]
Thanks @etorreborre. It's correct in the [`feature/ast`](https://github.com/brendanhay/amazonka/blob/3c46a6b9f8466b1804eb2fdcebba12c4a1e3a713/amazonka-s3/gen/Network/AWS/S3/ListParts.hs#L121) branch which avoids the issue that caused this in the first place, that is; fix one place, breaks another, due to overly coarse member name selection.

My focus is currently on getting those changes merged to `develop`, but if that drags out for whatever reason I'll make some stopgap fixes. Are you able to work around this in the short-term?

**Comment by etorreborre** [comment]
Yes we are currently using a [fork](https://github.com/ambiata/amazonka) but I'm reporting because we wouldn't like to diverge too much (also it helps others facing the same issue).

**Comment by brendanhay** [comment]
Fix verified in a38a3e9.

**Comment by etorreborre** [comment]
Thanks Brendan.
