### ISSUE TITLE
Parsing lists in amazonka-rds appears to be broken

### ISSUE THREAD

**Issue by iand675** [brendanhay/amazonka#131]
I've got a number of RDS instances that I want to work with, but they aren't being parsed out properly. The logging indicates that they are in the actual response body though:

``` haskell
{-# LANGUAGE OverloadedStrings #-}
module Main where
import Control.Lens
import Control.Monad.Trans
import Control.Monad.Trans.AWS
import System.IO
import Network.AWS.RDS

main :: IO ()
main = tryAWS printInstances

printInstances = do
  instances <- send describeDBInstances
  return $ instances ^.. ddbirDBInstances . traverse . dbiDBName

tryAWS m = do
  env <- getEnv NorthVirginia $ FromKeys (AccessKey __MY_KEY_HERE__) (SecretKey __MY_SECRET_HERE__)
  logger <- newLogger Trace stdout
  let withLogger = env & envLogger .~ logger 
  runAWST withLogger m >>= print
```

**Comment by charleso** [comment]
This is the same problem as for receiving SQS:

https://github.com/brendanhay/amazonka/pull/105

If you're interested, the problem is that it should be using "DBInstance" to lookup each instance, but currently it's using [member](https://github.com/brendanhay/amazonka/blob/develop/amazonka-rds/gen/Network/AWS/RDS/DescribeDBInstances.hs#L117). The [Java version](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-rds/src/main/java/com/amazonaws/services/rds/model/transform/DescribeDBInstancesResultStaxUnmarshaller.java#L50) as a point of reference.

As part of that PR above I've got another branch on our fork with the result of everything generated, and [you can see that it fixes that name](https://github.com/ambiata/amazonka/blob/gen/xml-list-member-name/amazonka-rds/gen/Network/AWS/RDS/DescribeDBInstances.hs#L117). I should warn you that we aren't using that branch (yet) and so I can't tell you what may have been broken as a result. I believe the correct fix is a little more complicated (see @brendanhay detailed response in the PR above).
