### ISSUE TITLE
AutoScaling - describeAutoScalingGroups

### ISSUE THREAD

**Issue by nhibberd** [brendanhay/amazonka#173]
As some background; The describe auto scaling groups [api](http://docs.aws.amazon.com/AutoScaling/latest/APIReference/API_DescribeAutoScalingGroups.html) defines its result as a list of [AutoScalingGroup](http://docs.aws.amazon.com/AutoScaling/latest/APIReference/API_AutoScalingGroup.html) which has a required field of `LaunchConfigurationName`. It also contains a list of [Instance](http://docs.aws.amazon.com/AutoScaling/latest/APIReference/API_Instance.html) which also have a required field of `LaunchConfigurationName`.

There is a situation in where the describe auto scaling group will return a list of `AutoScalingGroup` but with no `LaunchConfigurationName` member and `SerializationError`.

To reproduce the situation mentioned above:
- Create a LaunchConfiguration
- Create an AutoScaleGroup with the above launch configuration and a number of instances
- Delete the AutoScaleGroup ( goes into a terminate state while instances are shut down )
- Delete the LaunchConfiguration ( this is only possible when not attached to an active ASG ) 
- Call the `DescribeAutoScalingGroups` api
  - The ASG in the terminating state is returned in the list of members here, but as the LaunchConfiguration has been deleted it is not included in the response for both the group and the Instance's

Our current work around :hear_no_evil: https://github.com/ambiata/amazonka/commit/23697d012077e05709763a755d470c52dce240c9

**Comment by brendanhay** [comment]
Since this is a problem with the upstream definitions - I'll raise it there in case there is some historical discussion related to this. 

I see two possible fixes within `amazonka`:

1. Denote the `AutoScalingGroup` type is different for `DescribeAutoScalingGroups` vs `CreateAutoScalingGroup` etc. and have the generator output two separate types, one of which could be overriden.
2. Denote `LaunchConfigurationName` as optional for the type-value, but required for the smart constructor parameter-value.

Option (2) seems like less work at first glance and probably more convenient for the user not having multiple types floating around.

**Comment by brendanhay** [comment]
Actually, rather than me reflexively overcomplicating things - it appears `AutoScalingGroup` is only used by `DescribeAutoScalingGroups`. Oops.

In that case, I'll just add an `optionalField` for `LaunchConfigurationName` to the `autoscaling.json` generator configuration.

**Comment by brendanhay** [comment]
A question has been raised upstream: https://github.com/boto/botocore/issues/629

**Comment by brendanhay** [comment]
The regeneration of the above configuration updates is in 00c3cfb.

**Comment by nhibberd** [comment]
Awesome work, thanks.
