### ISSUE TITLE
ADT's for RDS text parameter

### ISSUE THREAD

**Issue by EduardSergeev** [brendanhay/amazonka#223]
All union parameter types in `RDS` are currently of type `Text` (i.e. [InstanceClass](https://github.com/ambiata/amazonka/blob/ambiata/amazonka-rds/gen/Network/AWS/RDS/CreateDBInstance.hs#L858), [Engine](https://github.com/ambiata/amazonka/blob/ambiata/amazonka-rds/gen/Network/AWS/RDS/CreateDBInstance.hs#L864-L869)), but it would be good to have them in the form of `data` [as it is done for EC2](https://github.com/brendanhay/amazonka/blob/develop/amazonka-ec2/gen/Network/AWS/EC2/Types/Sum.hs#L882-L936).

**Comment by endgame** [comment]
Looks like it's because unlike EC2 instance types, AWS doesn't enumerate these instance classes in the service definition:

https://github.com/boto/botocore/blob/d5a346e89cc27b685de3ca9d6f0deb32b27bf3ec/botocore/data/rds/2014-10-31/service-2.json#L3545-L3548

I'm going to close this, because manually enumerating these will be a maintenance PITA, but if @brendanhay disagrees then we can reopen it. In either case, it doesn't make important things impossible, so it's a post-2.0 issue.
