### ISSUE TITLE
PutObjectACL incorrectly uses `putXML` instead of `put`.

### ISSUE THREAD

**Issue by markhibberd** [brendanhay/amazonka#241]
It can not provide a body, if it does you will see something like:

```
[ServiceError] {
  service    = S3
  status     = 400 Bad Request
  code       = UnexpectedContent
  message    = Just This request does not support content
  request-id = Just AEC8FA44647E0C83
}
```

The fix to the generated code needs to be something like: https://github.com/ambiata/mismi/commit/7b3c906814466e59d1b0113df623b664eb6e63ac

This is verified to work as expected, but I don't have me head in the generator enough to be able to quickly make the change, I will have a look but perhaps not quickly.

**Comment by brendanhay** [comment]
It's fine, I'll take care of it. Thanks for raising.

**Comment by brendanhay** [comment]
The problem is caused by the fact that the [PUT Object ACL](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUTacl.html) request can be specified via Headers, or the XML body, but not both simultaneously. The fix you linked to in ambiata/mismi silently breaks the latter case of specifying an `AccessControlPolicy` in the body. 

In fact the generator will correctly use `put` vs `putXML` depending on the payload composition - but `putXML` itself is rendering an empty element when none is specified. (I suspect past-self did this deliberately.)  So if you use the headers to specify a `ObjectCannedACL` it'll break due to the empty root element. Conversely, setting no headers and using `poaAccessControlPolicy` should work.

Two possible fixes:

* Override the `PutObjectACL` request data type to drop the `poaAccessControlPolicy` field completely, thereby making it a headers only request, which will correctly use `put`.
* Make the `ToElement` typeclass return `Maybe Element` and have `put/postXML` correctly set the request body (or not).

The latter approach seems preferable, but may have unintended consequences if there are requests that in fact require an empty root XML element. I'll need to investigate this.
