### ISSUE TITLE
amazonka-kms: CreateKeyResponse contains Maybe KeyMetadata

### ISSUE THREAD

**Issue by rjosephwright** [brendanhay/amazonka#265]
Hi,

I'm wondering why `CreateKeyResponse` contains `KeyMetadata` as a `Maybe`. It seems that if the request succeeds, [it will contain the key metadata](http://docs.aws.amazon.com/kms/latest/APIReference/API_CreateKey.html#API_CreateKey_ResponseSyntax).

Here is some example code I wrote to retrieve a key ID if an alias already exists for the key, or to create the key and alias if it doesn't, and then return the key ID of the newly created key. It would be nicer without having to pattern match on the `Maybe KeyMetadata`. Is there a more idiomatic way of handling such scenarios?

```haskell
findOrCreateMasterKey :: KeyAlias -> IO (Maybe KeyId)
findOrCreateMasterKey alias = inAws $ do
  a <- send listAliases
  case keyIdForAliasP a alias of
    k@(Just _) -> return k
    Nothing -> do
      createKeyResponse <- send createKey
      let keyId = createKeyResponse ^? ckrsKeyMetadata . traverse . kmKeyId
      case keyId of
        Just k -> void . send $ createAlias alias k
        Nothing -> return ()
      return keyId
```

**Comment by brendanhay** [comment]
Apologies for the late reply. Since there is no metadata denoting what fields in a response are present (or not) in the [upstream service definitions](https://github.com/boto/botocore/blob/7dc06b0e554750b17ac3a3ca2af79734a3317b27/botocore/data/kms/2014-11-01/service-2.json#L2141-L2149), the fields are generated as `Maybe` so that semantics are preserved with the other generated languages (Python, Ruby, Java, Go etc.) which use null references.

In the cases where we assume (via common sense/documentation) that fields are always present they can denoted as such via [overrides](https://github.com/brendanhay/amazonka/blob/812af2f5a4bfced931e04e0739b9ba18eaa09b35/gen/config/kms.json#L6-L7).

For your example you could use `_Just` (from `Control.Lens.Prism`) instead of `. traverse .` to obtain the `kmKeyId`. Apart from that, it seems the `Maybe KeyId` return type only exists because `KeyMetadata` is a `Maybe`. You could handle the missing key metadata case as an error:

```haskell
findOrCreateMasterKey :: KeyAlias -> AWST (ExceptT IO) KeyId
findOrCreateMasterKey ka = do
    as <- send listAliases
    case keyIdForAlias ks as of
        Just kid -> kid
        Nothing  -> do
            rs  <- send createKey
            kid <- lift (rs ^? ckrsKeyMetadata . _Just . kmKeyId)
                ?? "Missing key metadata."
            void $ send (createAlias alias kid)
            pure kid

keyIdForAlias :: KeyAlias -> ListAliasesResponse -> Maybe KeyId
keyIdForAlias ka rs = undefined
           
-- From 'errors' / 'Control.Error.Util':

(??) :: Applicative m => Maybe a -> e -> ExceptT e m a
a ?? e = ExceptT $ pure (note e a)

note :: a -> Maybe b -> Either a b
note a = maybe (Left a) Right
```

Where `(??)` is used to annotate/signal the erroneous missing key metadata case, but ultimately it's only a stylistic difference.

Written on a phone, with all of the type-checking that implies.

**Comment by rjosephwright** [comment]
Thanks for the reply, I will give your approach a try.

I'm still wondering why `CreateKeyResponse` differs from, say, `GenerateDataKeyResponse`. The [specifications](https://github.com/boto/botocore/blob/7dc06b0e554750b17ac3a3ca2af79734a3317b27/botocore/data/kms/2014-11-01/service-2.json#L2365-L2381) don't look that different, but `GenerateDataKeyResponse` fields are not generated as `Maybe`s, whereas `CreateKeyResponse` fields are.

**Comment by brendanhay** [comment]
[https://github.com/brendanhay/amazonka/blob/812af2f5a4bfced931e04e0739b9ba18eaa09b35/gen/config/kms.json#L6-L7](Overrides) already exist for that particular response.

**Comment by rjosephwright** [comment]
I see. Thank you!
