### ISSUE TITLE
API Links are wrong.

### ISSUE THREAD

**Issue by joehillen** [brendanhay/amazonka#268]
I was browsing the docs and I noticed that the AWS API Reference links don't work.

https://hackage.haskell.org/package/amazonka-s3-1.3.7/docs/Network-AWS-S3-PutObject.html

links to

http://docs.aws.amazon.com/AmazonS3/latest/API/PutObject.html

but I think it should be

http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUT.html

**Comment by brendanhay** [comment]
Thanks - unfortunately I've been aware of this for some time. This is due to the generator expecting a certain documentation link format (Say, EC2/SQS etc.) and various services having completely different URL structures (such as S3). The current generator configuration simply prepends a static URL to a massaged version of the API operation name, which in S3's case is not easily predictable.

There are are a couple of possible fixes:

1. Support some kind of pattern substitution to allow the `config/*.json` to express a more diverse URL structure.
2. Remove the API Reference links completely.

I prefer 2. since the links are slowly finding their way into the upstream definitions. It means less work/code in the generator and although some services may have no links, this seems preferable to the incorrect ones currently there.

**Comment by joehillen** [comment]
I'm fine with 2. If you're using amazonka, you probably already know how to find the AWS docs.
