### ISSUE TITLE
Types in Network.AWS.STS.Credentials don't line up with Network.AWS.Auth.Credentials

### ISSUE THREAD

**Issue by tswelsh** [brendanhay/amazonka#357]
I am using `Network.AWS.STS.AssumeRole` to get an [STS Credentials object](https://hackage.haskell.org/package/amazonka-sts-1.4.5/docs/Network-AWS-STS.html#t:Credentials).  I was going to use the fields of that to make a [Network.AWS.Auth.Credentials](https://hackage.haskell.org/package/amazonka-1.4.5/docs/Network-AWS-Auth.html#t:Credentials) via the `FromSession` constructor but found I had to convert the `Text` values from the STS Credentials into the various newtypes over `ByteString` (`AccessKey`, `SecretKey`, `SessionToken`) that the `Network.AWS.Auth.Credentials` requires.

Is it possible for the fields of `Network.AWS.STS.Credentials` to have types that match the types of the arguments to  `FromSession`?  There is also a slight difference in naming - the former has fields `cAccessKeyId`, `cSecretAccessKey` which I am mapping on to things of type `AccessKey` and `SecretKey` respectively.  If they are all morally the same thing it feels like the types and names should align.

**Comment by davidchambers** [comment]
I just ran into this myself. Thanks for raising this issue, @tswelsh. :)

**Comment by brendanhay** [comment]
`amazonka-sts.Credentials` has [previously](https://github.com/brendanhay/amazonka/blob/e0c8fea840b44b6173fc59d4715c2b29b2acee18/amazonka-sts/gen/Network/AWS/STS/GetSessionToken.hs#L133-L136) been replaced by the internal [`amazonka-core.AuthEnv`](https://github.com/brendanhay/amazonka/blob/e0c8fea840b44b6173fc59d4715c2b29b2acee18/core/src/Network/AWS/Types.hs#L587-L592) type in the `develop` branch, and is planned to be released shortly as part of a probable `1.5.0` release.

The `AuthEnv` [lenses](https://github.com/brendanhay/amazonka/blob/e0c8fea840b44b6173fc59d4715c2b29b2acee18/core/src/Network/AWS/Types.hs#L620-L641) can then be used to extract types suitable for constructing your own `amazonka.Credentials`, or you can reconstruct the `amazonka.Env` directly if desired. This should obviate the need to have to convert `ByteString`s into the various `newtype`s.

At some point the existing `Credentials` will be renamed to `Discovery` or similar, and `AuthEnv` likewise to `Credentials` along with suitable `newEnv` additions, hopefully making this more intuitive. Although this change is not planned until a couple of other unrelated non-breaking fixes have first been released.

**Comment by brendanhay** [comment]
I'll share a snippet of a previous conversation regarding the use of STS `AssumeRole` and the credentials types here:

Since a majority of the individual `amazonka-*` library's types are generated, there's quite often duplication of primitive types that could be shared. I've updated `amazonka-sts` and `amazonka-iam` to use the same underlying credential types as you use for AuthN/AuthZ with `amazonka`.

In brief, The core `AuthEnv` environment which was previously only used internally (hence the naming):

https://github.com/brendanhay/amazonka/blob/dfe1ce5db10bba7d3fa7420d3da629731976047a/core/src/Network/AWS/Types.hs#L587-L642

Has supplanted the `Credentials` type previously available in `amazonka-sts`. The responses now return `AuthEnv` or `AccessKey`, `SecretKey`, and `SessionToken` and the same applies to `amazonka-iam`.

To use the `AuthEnv` returned by `AssumeRole` to update your current environment's authentication used for signing any requests within scope:

```import Control.Lens ((.~), (^.))

import Network.AWS

import qualified Control.Monad.Reader as Reader
import qualified Network.Amazonka.Env as Env
import qualified Network.Amazonka.STS as STS

assumeRole :: AuthEnv -> AWS a -> AWS a
assumeRole auth = Reader.local (Env.envAuth .~ Auth auth)

main :: IO ()
main = do
    env <- newEnv Discover

    runResourceT . runAWS env $ do
        -- Call 'AssumeRole' with the role ARN and session identifier:
        role <- STS.assumeRole "arn:" "session-name"

        -- Anything outside the scope of 'assumeRole' below will use
        -- the original credentials obtained from 'newEnv'.
        assumeRole (role ^. arrsCredentials) $ do
            -- Anything in here will use the credentials returned by 'STS.assumeRole'.
            return ()

        -- And here we're back to using the original credentials.
```

https://github.com/brendanhay/amazonka/blob/dfe1ce5db10bba7d3fa7420d3da629731976047a/amazonka-sts/gen/Network/AWS/STS/AssumeRole.hs#L192

An alternative if structuring things differently using say `amazonka-iam` which return only component parts of `AuthEnv`, you can use `fromTemporarySession`:

https://github.com/brendanhay/amazonka/blob/dfe1ce5db10bba7d3fa7420d3da629731976047a/amazonka/src/Network/AWS/Auth.hs#L169-L179

You'll need to update your `stack.yaml` until these changes go out in a release.

**Comment by tswelsh** [comment]
That's great, thank you! I'll try to remember to check the develop branch in future too.
