### ISSUE TITLE
GetAccountAuthorizationDetails should support pagination?

### ISSUE THREAD

**Issue by DaveCTurner** [brendanhay/amazonka#361]
The IAM function GetAccountAuthorizationDetails seems to return a paginated response, but the `amazonka` implementation does not have the appropriate instances to support using it with `paginate`.

**Comment by brendanhay** [comment]
The [service definition](https://github.com/boto/botocore/blame/8a28aa080f9115ff6b92adc0410da3da6b6ef6e7/botocore/data/iam/2010-05-08/paginators-1.json#L3) does indeed have this paginator, I believe it has been excluded from the generator because it was structurally incorrect. I'll see if a) it can be re-enabled, and b) if it works!

**Comment by brendanhay** [comment]
Scratch that, it was [re-enabled 6 months ago](https://github.com/brendanhay/amazonka/blame/018dd7f293acc389e30b94326a1815ca1b47ac59/amazonka-iam/gen/Network/AWS/IAM/GetAccountAuthorizationDetails.hs#L96), which version of `amazonka-iam` are you using?

**Comment by DaveCTurner** [comment]
Ah, apologies. I was on 1.4.3 which was the latest in a Stackage LTS until today. I see it was fixed in 1.4.4.
