### ISSUE TITLE
compile speed?

### ISSUE THREAD

**Issue by mwotton** [brendanhay/amazonka#414]
not a bug, and feel free to close this if you don't have time - it was suggested to me that you were probably the person compiling the biggest Haskell files around. I was hoping for some feedback on your experiences - do you get the impression that GHC is superlinear in the size of the file? I've got a single 100k line .hs file that just takes forever, I'm wondering if it'd be worth trying to split it up into chunks.

**Comment by brendanhay** [comment]
Apologies for the late reply, @mwotton. Rather than the size of the file - in most of my adhoc testing the resulting size of the core output seems to be the primary indicator of build time, namely alot of datatypes + deriving/instances will result in horrific compilation times (`amazonka-ec2` is a good case study here) particuarly with `Generic` it seems. A larger 'file' which consists of only values/expressions by contrast will compile very quickly .
