### ISSUE TITLE
Test against AWS?

### ISSUE THREAD

**Issue by LeifW** [brendanhay/amazonka#477]
I was thinking it would be handy to test against AWS. One benefit is hopefully people could know in advance whether what's in the repo works or not.
e.g.currently amazonka-glacier is missing an auth header, and sends the wrong format of requests for InitiateJob requests. amazonka-sdb sends the auth in the wrong style.
I could contribute some tests if this would be desired, e.g. for sdb a simple "list domains" request, and for glacier perhaps a "list jobs" request or similar. Both would check that the auth and the request format is at least correct. I believe the first 10,000 such requests each month are free for those services.

**Comment by naushadh** [comment]
An AWS mock could be used instead of relying on a live account/credential. Ex: https://github.com/localstack/localstack

**Comment by endgame** [comment]
Integration tests that boot a mock stack would be cool because we could CI them; I'd be more cautious about the bill that you'd get running integration tests against a live AWS account: since you need to test everything, the keys would have nearly unrestricted permissions, which would be a big risk.

A suite of manually-invoked tests masquerading as examples would be useful when trying to fix specific services and when developing tweaks to the files that live in `config/`. I'd look at a PR that creates a new package to hold these manual tests. Making them `executable` instead of `test-suite` in the cabal file is probably best so they don't get run by CI.

I'll close this issue now, because I think that answers the OP question, and otherwise it would stay open forever because there's no concept of what "done" would be otherwise.

**Comment by brendanhay** [comment]
Smoke tests that masquerade as examples would indeed be great - I would leave it up to individuals to run them, at their own expense, though. This was more or less what `./examples` was supposed to be - it just never got a whole lot of love.
