### ISSUE TITLE
override/required fields are not quite right for ec2

### ISSUE THREAD

**Issue by dysinger** [brendanhay/amazonka#59]
plan :: Options -> IO (Either Error ())
    plan _opts =
      do lgr <- newLogger Trace stdout
         env <- getEnv NorthVirginia Discover <&>
                envLogger .~
                lgr
         ts <- Text.pack . show <$> getTimestamp
         runAWST env $
           do say "Run " ts
              result0 <- sendCatch describeInstances
              case result0 of
                (Left err) -> say "Error " err
                -- Error SerializerError "EC2" "unable to find element
                -- \"keyName\" in nodes
                -- [\"instanceId\",\"imageId\",\"instanceState\",\"privateDnsName\",\"dnsName\",\"reason\",\"amiLaunchIndex\",\"productCodes\",\"instanceType\",\"launchTime\",\"placement\",\"kernelId\",\"monitoring\",\"privateIpAddress\",\"ipAddress\",\"groupSet\",\"architecture\",\"rootDeviceType\",\"rootDeviceName\",\"blockDeviceMapping\",\"virtualizationType\",\"clientToken\",\"tagSet\",\"hypervisor\",\"networkInterfaceSet\",\"ebsOptimized\"]"
                (Right response) ->
                  do forM_ (view dirReservations response) $
                       \x ->
                         say " " (x ^. rReservationId)
              result1 <- sendCatch describeVolumes
              case result1 of
                (Left err) -> say "Error " err
                -- Error SerializerError "EC2" "unable to find element
                -- \"iops\" in nodes
                -- [\"volumeId\",\"size\",\"snapshotId\",\"availabilityZone\",\"status\",\"createTime\",\"attachmentSet\",\"tagSet\",\"volumeType\",\"encrypted\"]"
                (Right response) ->
                  do forM_ (view dvrVolumes response) $
                       \x -> say " " (x ^. vVolumeId)
              result2 <- sendCatch describeSnapshots
              case result2 of
                (Left err) -> say "Error " err
                -- Result: Error SerializerError "EC2" "empty node list,
                -- when expecting a single node: Text"
                (Right response) ->
                  do forM_ (view dsrSnapshots response) $
                       \x ->
                         say " " (x ^. sSnapshotId)
              result3 <- sendCatch listBuckets
              case result3 of
                (Left err) -> say "Error " err
                -- WORKS GREAT!
                (Right response) ->
                  do forM_ (view lbrBuckets response) $
                       \x -> say " " (x ^. bName)

    say :: Show a => Build.Builder -> a -> AWST IO ()
    say msg = info . mappend msg . Build.stringUtf8 . show

    getTimestamp :: IO Integer
    getTimestamp = truncate <$> getPOSIXTime

**Comment by brendanhay** [comment]
Thanks, will investigate.

**Comment by brendanhay** [comment]
It seems there is a number of issues at play here:

* I've [incorrectly annotated](https://github.com/brendanhay/amazonka/blob/develop/gen/overrides/ec2.json#L151) `keyName` in `DescribeInstancesResponse` as required.
* I've [incorrectly annotated](https://github.com/brendanhay/amazonka/blob/develop/gen/overrides/ec2.json#L201) `iops` in `DescribeVolumesResponse` as required.
* The `DescribeSnapshots` error is a bit harder to debug, since the (de)serializer is basically saying it's found whatever [element node](https://github.com/brendanhay/amazonka/blob/develop/gen/overrides/ec2.json#L128) it was looking for, but it was erroneously empty.

I'll fix the first two in `develop` immediately, before looking at the third issue.

**Comment by brendanhay** [comment]
I believe the third issue listed above from your `DescribeSnapshots` request is related to an [incorrect annotation](https://github.com/brendanhay/amazonka/blob/83ba4af72b6234f282f336de74e8eb9a335e19b2/gen/overrides/ec2.json#L137) of `status`/`State`.

I've attempted to improve the error messages for nullary sum type deserialisation to propagate to the sum's `FromText` instance which all contain a [failure case](https://github.com/brendanhay/amazonka/blob/520713db23791a1bb7ef6325df0e2b652abb102a/amazonka-ec2/gen/Network/AWS/EC2/Types.hs#L5493) including the type in error message, instead of failing with the `FromText Text` instance's error message.

The next step is to verify it is indeed `state`/`Status` that is missing in the response and also remove it from the override.

**Comment by dysinger** [comment]
Heh. You are fast! I started a branch after I figured out what was going on last night (probably around the same time as you). 

Very nice library.  Thank you for creating it.  I'm hoping to contribute.

https://github.com/dysinger/amazonka/compare/override-mistakes?expand=1

"name" is also not required for ec2 images.  I've just been going through them & querying my 16 aws accounts (with 1000+ nodes).  Getting real data pumped in shows where the gaps are.

I can open a pull request for optional ec2 image name but it's probably not worth the p/r.  Can you fix it?

**Comment by dysinger** [comment]
I did a pull request anyway.

**Comment by brendanhay** [comment]
Fixed via #60.
