### ISSUE TITLE
Parameters necessary to compile dependency `text-icu` with Cabal on Mac

### ISSUE THREAD

**Issue by peterbecich** [brendanhay/amazonka#604]
I believe a library and parameters are necessary to compile `amazonka` and its dependency https://github.com/bos/text-icu with Cabal on a Mac.

The library `icu4c` is on Homebrew: https://github.com/haskell/haskell-ide-engine/issues/275

However, the solution inferred from https://github.com/haskell/haskell-ide-engine/issues/275 doesn't work:

```
cabal build all \
  --extra-lib-dirs=/usr/local/opt/icu4c/lib \
  --extra-include-dirs=/usr/local/opt/icu4c/include
```

The reason is: https://github.com/haskell/cabal/issues/2997

I have found this (from https://github.com/haskell/cabal/issues/2997#issuecomment-609608367) to work:
`cabal.project.local`
```
package *
  extra-include-dirs: /usr/local/opt/icu4c/include
  extra-lib-dirs: /usr/local/opt/icu4c/lib
```

**Comment by endgame** [comment]
@peterbecich I don't have a mac. Can you check for me whether the following `cabal.project.local` works?

```
package text-icu
  extra-include-dirs: /usr/local/opt/icu4c/include
  extra-lib-dirs: /usr/local/opt/icu4c/lib
```

The hope is that if this fix works, then this becomes only `text-icu`'s problem.

@lrworth maybe if you have a chance, you could point your mac at this too? I suspect we haven't seen this problem because nix fixes the paths up for us. Do you see this if error if you grab GHC from `ghcup` and use `cabal` without Nix?

**Comment by brendanhay** [comment]
These errors are specifically for `amazonka-gen` - the version in `develop` no longer has a direct dependency on `text-icu`.
