### ISSUE TITLE
Support Digital Ocean

### ISSUE THREAD

**Issue by mchaver** [brendanhay/amazonka#616]
Digital Ocean Spaces supports aws s3 sdk from other programming languages, but it has a few differences like region names. Region names are hard coded in amazonka. Can we get support for a region constuctor like `Custom Text`

**Comment by endgame** [comment]
Might be nice, but getting 2.0 ready to ship is more important. But I'd consider a PR if it didn't change too much other stuff along the way.

**Comment by endgame** [comment]
Actually, I think this is doable with the tools currently in `develop`:

You can override the endpoint of a service:
https://github.com/brendanhay/amazonka/blob/27e5fb472139b685244d4fdcc0eba50e04e24b4b/amazonka/src/Network/AWS/Endpoint.hs#L35

The service is provided by `Network.AWS.S3`:
https://github.com/brendanhay/amazonka/blob/develop/amazonka-s3/gen/Network/AWS/S3.hs#L23

And #597 switched to using `newtype` and pattern synonyms instead of enums, so you can construct your own.
