### ISSUE TITLE
Feature Request: Credentials supports `source_profile` in `.aws/config`

### ISSUE THREAD

**Issue by moso344** [brendanhay/amazonka#629]
Currently `Credentials` (`FromFile` and `Discover`) can't read `~/.aws/credentials` specified by `source_profile` in `~/.aws/config`.

### local `~/.aws/config`

```
[profile first]
region = ap-northeast-1

[profile second]
role_arn = arn:aws:iam::000000000000:role/Sample
source_profile = first
```

### local `~/.aws/credentials`

```
[first]
aws_access_key_id        = XXXXXXXXXXXXXXXXXXXX
aws_secret_access_key    = XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
aws_session_token        = XXX...
aws_security_token       = XXX...
x_principal_arn          = arn:aws:sts::000000000000:assumed-role/First/sample@example.com
x_security_token_expires = 2021-05-19T13:05:47+09:00
```

### env

```console
$ export AWS_PROFILE=second
$ export AWS_REGION=ap-northeast-1
```

### haskell

```haskell
sample :: IO GetCallerIdentityResponse
sample = do
  env <- newEnv Discover
  runResourceT . runAWS env $ send getCallerIdentity
```

```
*** Exception: InvalidFileError "/home/dan/.aws/credentials, key aws_access_key_id Couldn't find section: second"
```

**Comment by brendanhay** [comment]
Great request! Currently `~/.aws/config` is unsupported outside of a recently merged changed for `region`, specifically. The credential and configuration handling should be rewritten to match the [documentation](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html), which has changed (grown) quite a lot since this code was first written.

**Comment by endgame** [comment]
Probably too much effort to try and get it in for 2.0, but I'd consider a good PR that implements it.
