### ISSUE TITLE
Base `amazonka` package not in Stack LTS

### ISSUE THREAD

**Issue by kamek-pf** [brendanhay/amazonka#636]
Hi,

It looks like `amazonka` itself isn't in the latest Stack LTS anymore. All the other `amazonka-*` packages are though.
Is this intentional ?

**Comment by brendanhay** [comment]
No, not intentional. I assume it was evicted for whatever compatibility reason(s), but ideally the others should have been also.

**Comment by kamek-pf** [comment]
Ah, I see why now, `amazonka` depends on `unliftio-core` 0.1.*, but the current LTS depends on 0.2.14. 
Not sure how difficult it would be to update, but adding both as `extra-deps` works for now.

I'll let you decide what to do with this issue !

**Comment by endgame** [comment]
It'll be good to get this back into stackage eventually, but we'll need the 2.0 release on Hackage.

**Comment by ysangkok** [comment]
unliftio-core 0.1.2.0 doesn't compile on GHC 9 (because it disallows base 4.15), so it would be nice to allow the newer unliftio-core such that GHC 9 can be supported, if that is easy to do. Not sure I understand why this needs a 2.0 release. Probably I am missing context but I'm curious.

**Comment by endgame** [comment]
Two reasons:

1. AIUI, we need a hackage release for stackage to pick up.
2. Because we need to make decisions about what to cut or we'll never get something out the door. 2.0 is going to be huge as-is. I don't know if we currently build successfully against `unlfitio-core == 0.2.*` or not. If you can test that and/or provide a PR that adds the necessary support, then we might be able to merge it pre-2.0.

**Comment by ysangkok** [comment]
I found that `develop` does work on GHC 9 (with unliftio-core 0.2.*). But `release/1.7.0` (which isn't actually released to Hackage) also does, due to https://github.com/brendanhay/amazonka/pull/572 .

> we'll never get something out the door

Has it been decided to not make any 1.* releases? I was surprised to find that branch with fixes on them, without having an actual Hackage release.

**Comment by endgame** [comment]
Yes. An intermediate release will be too much work, and I'll burn out before 2.0 is ready. 1.x has had no release for years, another couple of months of no-release is a price I'm willing to pay if it means we get a new release at all.

**Comment by endgame** [comment]
Someone put it back into stackage, it seems. Closing.

**Comment by ysangkok** [comment]
I put it back, I also took the liberty of adding all the new packages I could find:

* https://github.com/commercialhaskell/stackage/pull/7070

One curious thing I noted is that the `v2` prefix is sometimes with a hyphen, sometimes not. See below.

Without hyphen:
- amazonka-wafv2
- amazonka-sesv2
- amazonka-maciev2
- amazonka-kinesisanalyticsv2
- amazonka-lexv2-models
- amazonka-greengrassv2
- amazonka-apigatewayv2
 
With hyphen:
- amazonka-resource-explorer-v2
- amazonka-pinpoint-sms-voice-v2

And one that has no v:
- amazonka-inspector2

**Comment by endgame** [comment]
Thank you for that.

Re: V2s: I think that's `botocore`'s fault. If you look at https://github.com/boto/botocore/tree/develop/botocore/data you will see a similar pattern. Trying to smooth over irregularities across the entire AWS API would be endless work for little gain, so "following AWS" makes us predictable and easier to understand for people coming from other ecosystems.
