### ISSUE TITLE
Branch structure

### ISSUE THREAD

**Issue by endgame** [brendanhay/amazonka#641]
There are branches `develop`, `main`, `master`, and `main-develop` in this repo. @brendanhay : ISTR you mentioned you wanted to rearrange these and nail down a branching workflow? Maybe we can delete or rename some of these refs to minimise confusion?

**Comment by endgame** [comment]
I think what I was thinking of was your notes at the bottom of the OP of #617

**Comment by brendanhay** [comment]
Yeah, that's correct. `main-develop` was an attempt of mine (recently, around the Neoproterozoic era) of trying to merge some major generator changes into `main` - while simultaneously deprecating `develop`. It turned out about as sensibly as the previous sentence reads.

Moving forward (say, RC) I'd like to have:

* `master (deprecated)`: Exists exactly as it is now. No more code will be merged or committed here.
* `develop (deprecated)`: Could exist up until we drop 2.0 or we could immediately switch development to `main` now. Will continue to exist similar to `master` so people's stack/cabal configurations don't break.
* `main (default)`: Create a _new_ `main` off `develop` and then use this exclusively moving forward as the sole source of truth.
* `main-develop (renamed)`: Can be renamed already - there's some salvagable code/experiments in there I'd like to reference but for all intents it's just a personal feature branch at this point. 

Does that make sense?

**Comment by endgame** [comment]
Yeah, makes sense. Let's do the renames when we cut RC, since at that point there should be no open PRs to disrupt. And maybe push a heading to the top of the root readme files in the dead branches?

**Comment by brendanhay** [comment]
Sounds good.
