### ISSUE TITLE
Bug: S3 GetObject considers 3xx HTTP status codes success

### ISSUE THREAD

**Issue by bitc** [brendanhay/amazonka#755]
If you use the wrong region and do a simple S3 `GetObject`, then the response is a 301 redirect.

The problem is that this library treats this as a successful response, and returns the AWS XML redirect page as the response body!

This can cause silent data corruption, for example if you have a download script and then happen to run it some day on a bucket in a different region, it will appear to run correctly but all the saved files will be corrupt, with no indication that there was any error.

The workaround I am using for now is `AWS.override` with `AWS.serviceCheck` to validate `200 <= status < 300` on all S3 calls. But I believe that this should be fixed in this library (hopefully in time for the 2.0 release)

**Comment by endgame** [comment]
Seems easy and important. I'll add it to the milestone. May need to add an extra type to the generator config, to enable plugin-based modification of how we react to responses or something.

**Comment by mjgpy3** [comment]
Throwing a :+1: on this since Freckle experienced it, as detailed here: https://github.com/brendanhay/amazonka/issues/770

**Comment by eborden** [comment]
I've done a bit of forensics on this. As far as I can tell this change was intentional.

The commit is here (https://github.com/brendanhay/amazonka/commit/d558759f3cda73e87a9d8ac9447c221a704e8a5d) referencing two issues (https://github.com/brendanhay/amazonka/issues/506 and https://github.com/brendanhay/amazonka/pull/507) that sought to change the exception behavior.

At this stage it seems the library just needs a clear stance on exceptional vs expected responses.

**Comment by pbrisbin** [comment]
> the library just needs a clear stance on exceptional vs expected responses

This is tricky. I looked at two sources to try and inform the stance,

- [Mozilla's categorization of HTTP Status codes](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status)
- [`Network.HTTP.Types.Status`'s "status is X" functions](https://hackage.haskell.org/package/http-types-0.12.3/docs/src/Network.HTTP.Types.Status.html#statusIsSuccessful)

Both make the distinction of _Redirection_ responses, which are neither _Success_ or _Error_ responses.

So, FWIW, I think one option is to go with:

-  `statusSuccess` as `>= 200 && < 300`
-  `statusRedirection` as ` >= 300 && < 400`
-  `statusError` as `>= 400` (or possibly `statusClientError` vs `statusServerError`)

(Basically, just mirror `Network.HTTP.Types.Status`'s own predicates.)

This gives more freedom through granularity to end-users (OP's workaround would look cleaner), but the library itself could also make different choices higher up the stack. For example, if we all agree that _S3 in particular_ is using "redirection responses" for success cases (I'm not sure I do, but) we could update `_svcCheck` to be `statusSuccess || statusRedirection`.

**Comment by endgame** [comment]
I'm now looking at this issue. I see two ways to decide whether a request is successful:

1. Classify response codes into `Informational | Success | Redirection | ClientError | ServerError` and find a way to let the caller customise that.
2. Decide which responses to consider as "successes" in a way that's more precise than "2xx only, or 2xx + 3xx?".

We could also try and follow redirects but I think that's worse because it could involve a lot of plumbing and people won't notice when they need to migrate.

I'm inclined to try success is `\x -> x == 304 || x >= 200 && x < 300`, and will put up a PR for people to test with.

**Comment by pbrisbin** [comment]
>  I see two ways to decide whether a request is successful:

Just to confirm some assumptions of mine:

- When talk about `_svcCheck`, we mean a mechanism that exists to define this behavior globally, by service, or by call
- There exists predicate methods like `statusIsSuccessful`, to make it easy to use this mechanism
- There exists a default `_svcCheck` for `S3` defined by the library
- Today, that check is `statusIsSuccessful`, which was changed from 200...299, to 200...399

If this is all true, I believe my suggestion above is still best. It's a version of (1), but may diverges on details?

- Define `statusIs{Whatever}` to classify as you've listed
- Define `_svcCheck = statisIsSuccessful || statusIsRediction` for `S3`
- :tada: This is behavior neutral, but
- :tada: Users can modify any `_svcCheck` as they wish, to go back to 200...299 behavior, special-case 304, or anything else

I struggle to see a downside to this approach, except maybe effort?

> I'm inclined to try success is `\x -> x == 304 || x >= 200 && x < 300`, and will put up a PR for people to test with.

Taking off my "Amazonka contributor" hat, and putting on my "Freckle Engineer" hat ^ this is the behavior we previously coded to and would allow us to pull our workaround, so if that's the direction you all pick, SGTM.
