### ISSUE TITLE
ETag in S3 responses are double-quoted

### ISSUE THREAD

**Issue by brendanhay** [brendanhay/amazonka#76]
Due to the quoted ETag header format not correctly being accounted for.

Can be fixed in the short-term by implementing a custom `FromText` instance [here](https://github.com/brendanhay/amazonka/blob/bc5c34ed8325d81c936d1028be0595f58d1530c1/amazonka-s3/src/Network/AWS/S3/Internal.hs#L76). This would account for both cases (quoted and unquoted).

**Comment by rjmac** [comment]
I'm fairly sure keeping the double-quotes is actually correct, because an [ETag according to the spec](http://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html#sec3.11) is either a quoted-string or `W/` followed by a quoted-string (so, for example `W/"asdf"` is a valid etag).  All the etags returned by S3 are of  the first form (and it's honestly unlikely it'd ever return a weak etag) but it still seems more correct to not strip the quotes.

**Comment by brendanhay** [comment]
Hah, thanks @rjmac. Not entirely sure why I thought otherwise, I should have read the spec ..
