### ISSUE TITLE
Consider releasing amazonka-core-1.6.1.1 with Aeson 2 compatibility 

### ISSUE THREAD

**Issue by alexbiehl** [brendanhay/amazonka#771]
It seems that Amazonka 2 is work in progress and probably takes a bit more time to mature. Also it looks like it will introduce quite a few breaking changes to the API. 

In the meantime the community is switching over to Aeson 2. At Scarf we found that amazonka-core-1.6.1 is one of the last blockers for our way to Aeson 2. We patched amazonka-core to work with both aeson < 2 and aeson > 2, you can find the (small) patch [here](https://github.com/scarf-sh/amazonka/tree/alex/aeson-2).

From what I can tell amazonka-core is the only package from the Amazonka family that needs adjustments to work with newer Aesons and maybe it's easy enough to make another release. It looks like if there was a release 1.6.1.1 it would satisfy the `> 1.6.1 && < 1.6.2` constraint on the various amazonka packages.

**Comment by endgame** [comment]
Thank you for the patch. Unfortunately, this probably isn't going to happen. My Hackage account doesn't have upload rights for amazonka packages, and I don't know what Brendan is up to at the moment.

Latest `main` supports `aeson-2.0`, and several companies have moved across. I'd strongly recommend doing that - my work has been running off latest `main` since before RC1 last November, so it's had plenty of time to stabilise. The new way of maintaining enums alone is worth the switch because it massively improves compile time, GHC memory usage, and no longer explodes when AWS extends an enum. If you can't switch over right now, I'd suggest you keep maintaining your private fork.

I'll close this for now, and if @brendanhay is around and wants to cut 1.6.1.1 for `amazonka-core`, he can reopen and do that.

**Comment by mbj** [comment]
BTW: I found amazonka-2 even if its not released to be more stable/easier to code against than the releases on hackage.
