### ISSUE TITLE
APIGatewayManagementAPI is not deployed to hackage?

### ISSUE THREAD

**Issue by stevemao** [brendanhay/amazonka#784]
https://github.com/brendanhay/amazonka/tree/main/lib/services/amazonka-apigatewaymanagementapi
the links to hackage are broken.

**Comment by endgame** [comment]
Many new service definitions are not on Hackage yet, and won't be until 2.0 is released. Until then, you should use latest `main`, which has had a _lot_ of development since the last Hackage release and reached RC1 late last year.

https://github.com/brendanhay/amazonka/discussions/716 has instructions for how to do this, for both cabal and stack.
