### ISSUE TITLE
Version 1.6.1 on Hackage does not match tag 1.6.1

### ISSUE THREAD

**Issue by robwithhair** [brendanhay/amazonka#937]
Version 1.6.1 on Hackage does not seem to be the same as Tag 1.6.1.  Specifically, the aeson version requirements.  

I don't know if there is a way to re-generate the data on Hackage, but if not maybe a minor patch from 1.6.1, just to get the latest updates would be desirable.

**Comment by endgame** [comment]
Version 1.6.1 is incredibly outdated, and will not see further updates. We are currently testing the second release candidate of 2.0: https://github.com/brendanhay/amazonka/discussions/927 (you should also click through to the RC1 release announcement, which has more migration information).

The code on branch `main` is very stable, and I have been running it in production at work for a long time without issue, so I recommend you use that. The RC announcements have instructions for importing code from git, for your build tool of choice.

**Comment by endgame** [comment]
OK, that's good. I was worried you hadn't found the newer code and was stuck trying to work with only the Hackage releases. But yeah, things have advanced so far since 1.6.1 that it's just not worth cutting a new release.

If you do need migration assistance, please post on the discussion thread, or feel free to open a new issue. I hope to get the `aeson` bound stuff sorted out and hopefully that's the last release blocker.
