### ISSUE TITLE
amazonka base revisions prevent building in Stackage Nightly!

### ISSUE THREAD

**Issue by juhp** [brendanhay/amazonka#988]
It is seems amazonka packages got revised to base < 4.19 on Hackage:
see for example https://hackage.haskell.org/package/amazonka-2.0/revisions/

Given that is was building is this really correct?
Maybe the intention was `base < 4.20`??

cc @JackKelly-Bellroy ?

**Comment by endgame** [comment]
That was me, as maintainer and as Hackage Trustee.

According to [Base Package (HaskellWiki)](https://wiki.haskell.org/Base_package), `base-4.19` corresponds to GHC 9.8, and if the linked issue is correct, only ~20 of the ~330 `amazonka-*` packages were compiling with GHC 9.8. Missing from that list is `amazonka` itself (necessary for user programs to make AWS calls in an ergonomic way) as are bindings for core AWS services like S3, Lambda, EC2, and IAM. Any service which has a record that shares a field name with any other record in the same service will fail to compile because [GHC 9.8 changed (for the better) where you need to place `{-# LANGUAGE DuplicateRecordFields #-}`](https://gitlab.haskell.org/ghc/ghc/-/issues/24317). See #969 for the original Amazonka bug, #972 for the PR to fix the generator, and #973 for the regeneration of service bindings.

So in my view, yes, the bounds revisions were largely correct. If you have evidence that this is not the case for certain packages and that re-revising bounds will improve things for your workloads (should I be raising the `base` upper bound on the packages listed in your linked Stackage issue?), then I can raise the upper bound for the 2.0 releases on Hackage.

*****

Also, a request: I am _keenly_ aware of the important role Amazonka plays to a number of people's AWS-using efforts (hobbyist, startup, and corporate) and that a viable AWS SDK makes Haskell a much more practical language for many workloads. While I'm grateful that Bellroy pays me to maintain Amazonka in a way that benefits everyone, I have other responsibilities at work and have to split Amazonka maintenance across personal and work time. I **do** try to take "great care" with my work on Amazonka, but mistakes sometimes happen; the alternative is excessive timidity and an inability to make fundamental fixes. My work here has stalled for a few months, for a few reasons, and I am trying to get things moving again in advance of ZuriHac. If I'm just gonna get chewed out for my best efforts, then it makes pushing things forward a much less attractive and fulfilling proposition. Please consider how you phrase your missives, and how their recipients will react to them.

**Comment by juhp** [comment]
Okay thanks for responding so fast: sorry I may have "pulled the trigger too fast" - you are right it's not that many packages...

**Comment by juhp** [comment]
I removed the accusatory sentence from the description, sorry again - I should have checked more carefully on the status: though I couldn't see any obvious recent ticket here immediately.

I know time is limited for all of us: a heads-up or stackage removal could have helped too - thanks again for the quick response and correcting me.

**Comment by endgame** [comment]
I appreciate that mate, thank you. I've edited out my prickly response, too, so we can call it even.
