### ISSUE TITLE
Inconsistent version bound between github and hackage

### ISSUE THREAD

**Issue by jchia** [brendanhay/amazonka#999]
There is a discrepancy in base upper bound between the v2.0 github code and the v2.0 hackage package description:
https://github.com/brendanhay/amazonka/blob/e081929d5a81f30397c9c9a219b154da1a922fb8/lib/amazonka/amazonka.cabal#L75
https://hackage.haskell.org/package/amazonka-2.0/amazonka.cabal

The former has `base >=4.12 && <5` while the latter has `base >=4.12 && <4.19`. Which upper bound is right? Can the two be made to agree? I discovered the issue trying to figure out why I can't use amazonka with GHC 9.8. I hope that amazonka is actually usable with GHC 9.8 and the hackage side gets fixed.

**Comment by endgame** [comment]
Thank you for your question.

> Which upper bound is right?

Both. The 2.0 release on Hackage does not compile with GHC 9.8 and has had its `base` bound revised to reflect this. The code currently on `master` has been fixed to compile with GHC 9.8 (the meaning of the `DuplicateRecordFields` extension changed).

> Can the two be made to agree?

No, because they're describing different things. One describes the bound on the 2.0 release, and the other describes the bounds at the head of the `master` branch.

Until a new release is made on Hackage, if you want to use GHC 9.8, you will have to import it from git. The old RC2 release announcement has instructions for how to do this with `cabal` and `stack`: https://github.com/brendanhay/amazonka/discussions/716
